### ISSUE TITLE
MGC support for GWAPI v1

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#630]
**What**

V1 of GWAPI is approaching we need to start testing with the new resources. https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.0.0-rc2

**How**

- [x] Update our GWAPI resources, install and create TLS and DNS policies 
- [x] update our GWAPI dependencies in the Gateway controller
- [x] #665 
- [x] update kuadrant-operator version which supports GWAPI v1 GA.
- [x] Update Gateway API Resources in the docs files to be V1

**Comment by laurafitzgerald** [comment]
WIP Branch https://github.com/laurafitzgerald/multicluster-gateway-controller/tree/gh-630

**Comment by laurafitzgerald** [comment]
There's some discussion at https://kubernetes.slack.com/archives/C05J0D0V525/p1698851598969379 about an issue I faced due to rules being too costly for httproutes when it comes to parentRef.

kuadrant-operator have logged it here [GEP: Add Name to HTTPRouteRule and HTTPRouteMatch · Issue #995 · kubernetes-sigs/gateway-api](https://github.com/kubernetes-sigs/gateway-api/issues/995#issuecomment-1787005682)

And have a solution on their side https://github.com/Kuadrant/kuadrant-operator/pull/286/commits/56a9a346b38907f93cff17b4935467fd0e5c17a6

It's blocking us from running our integration tests because the environment fails on CRD creation producing the following error 

```
unable to install CRDs onto control plane: unable to create CRD instances: unable to create CRD \"httproutes.gateway.networking.k8s.io\": CustomResourceDefinition.apiextensions.k8s.io \"httproutes.gateway.networking.k8s.io\" is invalid: [spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[parentRefs].x-kubernetes-validations[0].rule: Forbidden: estimated rule cost exceeds budget by factor of more than 100x (try simplifying the rule, or adding maxItems, maxProperties, and maxLength where arrays, maps, and strings are declared), spec.versions[0].schema.openAPIV3Schema.properties[spec].properties[parentRefs].x-kubernetes-validations[0].rule: Forbidden: contributed to estimated rule cost total exceeding cost limit for entire OpenAPIv3 schema, spec.versions[0].schema.openAPIV3Schema: Forbidden: x-kubernetes-validations estimated rule cost total for entire OpenAPIv3 schema exceeds budget by factor of more than 100x (try simplifying the rule, or adding maxItems, maxProperties, and maxLength where arrays, maps, and strings are declared)]
```

**Comment by laurafitzgerald** [comment]
For running through the walkthrough one issue is faced for the istio class gateway, which is that the Programmed status remains unknown. 

This could be addressed by https://github.com/istio/istio/commit/73e4596b49e1462048fe781b672f552b37a4214f which has been cherrypicked to release 1.20.0 of istio. We are currently running 1.17.0.

1.20.0-beta.0 is available https://hub.docker.com/r/istio/pilot/tags but we may have a short wait for 1.20.0 to be available. 

Update the following https://github.com/search?q=repo%3AKuadrant%2Fmulticluster-gateway-controller%201.17.0&type=code to move to the new version once it's available.
